In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\aditya\appdata\local\programs\python\python312\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aditya\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aditya\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aditya\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aditya\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\aditya\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.1'

In [4]:
# 1. Dataframe
df = pd.DataFrame([11,23,34], columns =['Col_Name'])
print(df)

   Col_Name
0        11
1        23
2        34

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data = {
    'Name':['Madhav','Vivek','Lalita','Rishabh'],
     'Age': [16,20,29,34],
      'salary': [90000,70000,50000,30000]
}

In [7]:
df = pd.DataFrame(data)
print(df)

      Name  Age  salary
0   Madhav   16   90000
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [8]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
# 2. Basic Dataframe Understanding

In [10]:
df.head(2) #top rows

     Name  Age  salary
0  Madhav   16   90000
1   Vivek   20   70000

In [11]:
df.tail(2) # last row

      Name  Age  salary
2   Lalita   29   50000
3  Rishabh   34   30000

In [12]:
df.shape

(4, 3)

In [13]:
df.columns

Index(['Name', 'Age', 'salary'], dtype='object')

In [14]:
df.rename(columns = {'salary': 'Monthly_Salary'},inplace=True)

In [15]:
df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1    Vivek   20           70000
2   Lalita   29           50000
3  Rishabh   34           30000

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(data)
print(df)

      Name  Age  salary
0   Madhav   16   90000
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [19]:
df.describe()

             Age        salary
count   4.000000      4.000000
mean   24.750000  60000.000000
std     8.220908  25819.888975
min    16.000000  30000.000000
25%    19.000000  45000.000000
50%    24.500000  60000.000000
75%    30.250000  75000.000000
max    34.000000  90000.000000

In [20]:
#2. Save and load data from CSV

In [21]:
df.to_csv('Test_data.csv',index=False)

In [22]:
load_df=pd.read_csv('Test_data.csv')
load_df

      Name  Age  salary
0   Madhav   16   90000
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [23]:
# 4. Rows & Columns-Selection

In [24]:
#select column
df[['Name']]#single column
df[['Name','Age']]

      Name  Age
0   Madhav   16
1    Vivek   20
2   Lalita   29
3  Rishabh   34

In [25]:
# Select rows
#loc - index name based
df.loc[df.Name=='Vivek']
df.loc[(df.Name=='Vivek')&(df.salary>=70000)]

    Name  Age  salary
1  Vivek   20   70000

In [26]:
#iloc - index-value based
# df.iloc[0]
df.iloc[0:2]  #[start:stop:step]

     Name  Age  salary
0  Madhav   16   90000
1   Vivek   20   70000

In [27]:
# 5. filter datframe

In [28]:
df

      Name  Age  salary
0   Madhav   16   90000
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [29]:
df_age_filter = df[df['Age'] >= 18]

In [30]:
df_age_filter

      Name  Age  salary
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [31]:
df.where(df['Age'] >= 18)

      Name   Age   salary
0      NaN   NaN      NaN
1    Vivek  20.0  70000.0
2   Lalita  29.0  50000.0
3  Rishabh  34.0  30000.0

In [32]:
df.where(df['Age'] >= 18,other = "not Eligible")

           Name           Age        salary
0  not Eligible  not Eligible  not Eligible
1         Vivek            20         70000
2        Lalita            29         50000
3       Rishabh            34         30000

In [33]:
#6 . Rowsand Columns - Operation (Add,Update,Delete)

In [34]:
df

      Name  Age  salary
0   Madhav   16   90000
1    Vivek   20   70000
2   Lalita   29   50000
3  Rishabh   34   30000

In [35]:
# add new column
df['Team']= ['CEO','CTO','HR','DA']
df

      Name  Age  salary Team
0   Madhav   16   90000  CEO
1    Vivek   20   70000  CTO
2   Lalita   29   50000   HR
3  Rishabh   34   30000   DA

In [36]:
df['Bonus'] =df['salary']* 0.2 
df

      Name  Age  salary Team    Bonus
0   Madhav   16   90000  CEO  18000.0
1    Vivek   20   70000  CTO  14000.0
2   Lalita   29   50000   HR  10000.0
3  Rishabh   34   30000   DA   6000.0

In [37]:
# add new row
df.loc[len(df)] = ['Abhishek',21,25000,'IT',5000]
df

       Name  Age  salary Team    Bonus
0    Madhav   16   90000  CEO  18000.0
1     Vivek   20   70000  CTO  14000.0
2    Lalita   29   50000   HR  10000.0
3   Rishabh   34   30000   DA   6000.0
4  Abhishek   21   25000   IT   5000.0

In [38]:
#delete value - row and column values

In [39]:
df.drop(df[df.Name == 'Rishabh'].index)

       Name  Age  salary Team    Bonus
0    Madhav   16   90000  CEO  18000.0
1     Vivek   20   70000  CTO  14000.0
2    Lalita   29   50000   HR  10000.0
4  Abhishek   21   25000   IT   5000.0

In [40]:
df.drop('Bonus',axis=1,inplace=True) #drop column

In [41]:
df

       Name  Age  salary Team
0    Madhav   16   90000  CEO
1     Vivek   20   70000  CTO
2    Lalita   29   50000   HR
3   Rishabh   34   30000   DA
4  Abhishek   21   25000   IT

In [42]:
#df.drop(['Bonus','Team'],axis=1) #delete multiple columns

In [43]:
#sort value
df.sort_values('salary') #decending order

       Name  Age  salary Team
4  Abhishek   21   25000   IT
3   Rishabh   34   30000   DA
2    Lalita   29   50000   HR
1     Vivek   20   70000  CTO
0    Madhav   16   90000  CEO

In [44]:
#7 working with date value

In [45]:
df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03','2023-03-12']

In [46]:
df

       Name  Age  salary Team         DOJ
0    Madhav   16   90000  CEO  2024-01-01
1     Vivek   20   70000  CTO  2024-01-15
2    Lalita   29   50000   HR  2024-03-28
3   Rishabh   34   30000   DA  2024-03-03
4  Abhishek   21   25000   IT  2023-03-12

In [47]:
df['DOJ'].dtype

dtype('O')

In [48]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [49]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [50]:
df1 = df

In [51]:
df

       Name  Age  salary Team        DOJ
0    Madhav   16   90000  CEO 2024-01-01
1     Vivek   20   70000  CTO 2024-01-15
2    Lalita   29   50000   HR 2024-03-28
3   Rishabh   34   30000   DA 2024-03-03
4  Abhishek   21   25000   IT 2023-03-12

In [52]:
df1=df

In [53]:
df1['DOJ2'] = ['01-01-2025','15-01-2025','28-03-2025','03-03-2025','04-05-2026']

In [54]:
df1

       Name  Age  salary Team        DOJ        DOJ2
0    Madhav   16   90000  CEO 2024-01-01  01-01-2025
1     Vivek   20   70000  CTO 2024-01-15  15-01-2025
2    Lalita   29   50000   HR 2024-03-28  28-03-2025
3   Rishabh   34   30000   DA 2024-03-03  03-03-2025
4  Abhishek   21   25000   IT 2023-03-12  04-05-2026

In [55]:
df1['DOJ2'].dtype

dtype('O')

In [56]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'],format = '%d-%m-%Y')

In [57]:
df1

       Name  Age  salary Team        DOJ       DOJ2
0    Madhav   16   90000  CEO 2024-01-01 2025-01-01
1     Vivek   20   70000  CTO 2024-01-15 2025-01-15
2    Lalita   29   50000   HR 2024-03-28 2025-03-28
3   Rishabh   34   30000   DA 2024-03-03 2025-03-03
4  Abhishek   21   25000   IT 2023-03-12 2026-05-04

In [58]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [59]:
df1

       Name  Age  salary Team        DOJ       DOJ2
0    Madhav   16   90000  CEO 2024-01-01 2025-01-01
1     Vivek   20   70000  CTO 2024-01-15 2025-01-15
2    Lalita   29   50000   HR 2024-03-28 2025-03-28
3   Rishabh   34   30000   DA 2024-03-03 2025-03-03
4  Abhishek   21   25000   IT 2023-03-12 2026-05-04

In [60]:
df = df.drop('DOJ2',axis=1)
df

       Name  Age  salary Team        DOJ
0    Madhav   16   90000  CEO 2024-01-01
1     Vivek   20   70000  CTO 2024-01-15
2    Lalita   29   50000   HR 2024-03-28
3   Rishabh   34   30000   DA 2024-03-03
4  Abhishek   21   25000   IT 2023-03-12

In [61]:
 # extract year,month,week,day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
4      Sunday
Name: DOJ, dtype: object

In [62]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2023-06-10
Name: DOJ, dtype: datetime64[ns]

In [63]:
# Handling mising value

In [64]:
df

       Name  Age  salary Team        DOJ
0    Madhav   16   90000  CEO 2024-01-01
1     Vivek   20   70000  CTO 2024-01-15
2    Lalita   29   50000   HR 2024-03-28
3   Rishabh   34   30000   DA 2024-03-03
4  Abhishek   21   25000   IT 2023-03-12

In [65]:
df.isnull()

    Name    Age  salary   Team    DOJ
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False

In [66]:
import numpy as np

In [67]:
df.loc[df.Name=='Vivek','salary'] = np.nan

In [68]:
df

       Name  Age   salary Team        DOJ
0    Madhav   16  90000.0  CEO 2024-01-01
1     Vivek   20      NaN  CTO 2024-01-15
2    Lalita   29  50000.0   HR 2024-03-28
3   Rishabh   34  30000.0   DA 2024-03-03
4  Abhishek   21  25000.0   IT 2023-03-12

In [69]:
df.isnull().sum()

Name      0
Age       0
salary    1
Team      0
DOJ       0
dtype: int64

In [70]:
df.fillna(0)

       Name  Age   salary Team        DOJ
0    Madhav   16  90000.0  CEO 2024-01-01
1     Vivek   20      0.0  CTO 2024-01-15
2    Lalita   29  50000.0   HR 2024-03-28
3   Rishabh   34  30000.0   DA 2024-03-03
4  Abhishek   21  25000.0   IT 2023-03-12

In [88]:
# 9 . Aggregation and group by

In [78]:
df['Month'] = [1,1,3,3,3]

In [79]:
df['Name'].value_counts()

Name
Madhav      1
Vivek       1
Lalita      1
Rishabh     1
Abhishek    1
Name: count, dtype: int64

In [80]:
df[df['Month']==1].value_counts()

Name    Age  salary   Team  DOJ         Month
Madhav  16   90000.0  CEO   2024-01-01  1        1
Name: count, dtype: int64

In [81]:
df

       Name  Age   salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1     Vivek   20      NaN  CTO 2024-01-15      1
2    Lalita   29  50000.0   HR 2024-03-28      3
3   Rishabh   34  30000.0   DA 2024-03-03      3
4  Abhishek   21  25000.0   IT 2023-03-12      3

In [82]:
df[df['Month']==1].value_counts()

Name    Age  salary   Team  DOJ         Month
Madhav  16   90000.0  CEO   2024-01-01  1        1
Name: count, dtype: int64

In [ ]:
# aggregation based on group by

In [83]:
df.groupby('Month')['salary'].sum()

Month
1     90000.0
3    105000.0
Name: salary, dtype: float64

In [84]:
df.groupby('Month')['salary'].mean()

Month
1    90000.0
3    35000.0
Name: salary, dtype: float64

In [86]:
df.groupby('Month').agg({'salary':'mean','Name':'count'})

        salary  Name
Month
1      90000.0     2
3      35000.0     3

In [87]:
# Concatenate and merge Dataframe (JOINS)

In [88]:
df1 =pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})

In [89]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [90]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Score':[88,98,78,79]})

In [91]:
df2

   ID  Score
0   1     88
1   2     98
2   3     78
3   4     79

In [92]:
pd.concat([df1,df2],axis=0) # row level / top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   98.0
2   3  NaN   78.0
3   4  NaN   79.0

In [93]:
pd.concat([df1,df2],axis=1) # cloumn level / side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     98
2  3.0    C   3     78
3  NaN  NaN   4     79

In [94]:
# merge = join
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     78

In [96]:
pd.merge(df1,df2,how='left',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     78

In [97]:
pd.merge(df1,df2,how='right',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     78
3   4  NaN     79

In [98]:
pd.merge(df1,df2,how='outer',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     78
3   4  NaN     79

In [99]:
pd.merge(df1,df2,how='left',left_on='ID',right_on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     98
2   3    C     78